[package]
name = "osintbuddy"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
confik = "0.14"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls", "postgres", "json" ] }
dotenvy = "0.15.7"
sqids = "0.4.2"
actix-cors = "0.7.1"
serde_json = "1.0.140"
